/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:97075a50-ff98-4601-bb54-e375f58457c9",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_hJSFWIqZa",
    "aws_user_pools_web_client_id": "1kk9i28kv6e145nmicckmu1alj",
    "oauth": {}
};


export default awsmobile;
